
### enriched occupations

GET https://jobed-connect-api.jobtechdev.se/v1/enriched_occupations?occupation_id=fg7B_yov_smw&include_metadata=true


#### search by text

POST https://jobed-connect-api.jobtechdev.se/v1/occupations/match-by-text?input_text=front%20end&input_headline=systemutvecklare&limit=10&offset=0&include_metadata=false
Content-Type: application/json

### get education form

GET https://jobed-connect-api.jobtechdev.se/v1/searchparameters/education_forms


### get education type

GET https://jobed-connect-api.jobtechdev.se/v1/searchparameters/education_types



### get educations

GET https://jobed-connect-api.jobtechdev.se/v1/educations?query=kock&education_type=kurs&education_form=h%C3%B6gskoleutbildning&distance=false&filter_education_plan_exists=false


### get about education: id

GET https://jobed-connect-api.jobtechdev.se/v1/educations/i.fbr.69199.400296



### get 

GET https://jobed-connect-api.jobtechdev.se/v1/searchparameters/municipalities