
### enriched occupations

GET https://jobed-connect-api.jobtechdev.se/v1/enriched_occupations?occupation_id=2tSL_RP2_jUP&include_metadata=false


#### search by text

POST https://jobed-connect-api.jobtechdev.se/v1/occupations/match-by-text?input_text='kock'&limit=10&offset=0&include_metadata=false
Content-Type: application/json

### get education form

GET https://jobed-connect-api.jobtechdev.se/v1/searchparameters/education_forms


### get education type

GET https://jobed-connect-api.jobtechdev.se/v1/searchparameters/education_types



#### get kommuner

GET https://jobed-connect-api.jobtechdev.se/v1/searchparameters/municipalities